version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestapi
    ports:
      - "5432:5432"  # Bu port Render tarafından otomatik yönetilecek
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
      DB_DATABASE: nestapi
      ACCESS_TOKEN_SECRET_KEY: qwelkjr12314qwlşdop2312312
      ACCESS_TOKEN_EXPIRE_TIME: 30m
      PORT: 3000  # Render, PORT ortam değişkeniyle dinamik portu atar
    ports:
      - "3000:3000"  # Render'da otomatik olarak yönlendirilecektir
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
